backend-create:
	./scripts/create-backend.sh

backend-list:
	./scripts/list-backend.sh

backend-destroy:
	./scripts/destroy-backend.sh

deploy:
	./scripts/terraform-deploy.sh

audit:
	./scripts/audit-resources.sh

security:
	./scripts/validate-security.sh

costs:
	./scripts/audit-costs.sh

destroy:
	./scripts/terraform-destroy.sh
